apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  releaseName: openebs
  chart:
    spec:
      chart: openebs
      version: "4.3.3"
      sourceRef:
        kind: HelmRepository
        name: openebs
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
    engines:
      replicated:
        mayastor:
          enabled: false
    loki:
      enabled: false
      localpvScConfig:
        enabled: false
    minio:
      enabled: false