apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  releaseName: openebs
  chart:
    spec:
      chart: openebs
      version: "4.3.3"
      sourceRef:
        kind: HelmRepository
        name: openebs
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
    zfs-localpv:
      zfsNode:
        encrKeysDir: /var/openebs/keys

    engines:
      replicated:
        mayastor:
          enabled: false
    loki:
      enabled: true

      localpvScConfig:
        loki:
          basePath: "/var/openebs/{{ .Release.Name }}/localpv-hostpath/loki"

      loki:
        schemaConfig:
          configs:
            - from: 2024-04-01
              store: tsdb
              object_store: filesystem
              schema: v13
              index:
                prefix: loki_index_
                period: 24h
        commonConfig:
          replication_factor: 1
        storage:
          type: filesystem

      singleBinary:
        replicas: 1
        drivesPerNode: 1
        persistence:
          enabled: true

      minio:
        enabled: false

        #FIXME: Loki are mountpath-ul la PVC in /var/local/.... , path care nu merge pe talos. Ori schimbi la /var/openebs/.... ori nu mai folosesti