apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  releaseName: openebs
  chart:
    spec:
      chart: openebs
      version: "4.4.0"
      sourceRef:
        kind: HelmRepository
        name: openebs
  interval: 60m
  install:
    remediation:
      retries: 3